# -*- coding: utf-8 -*-
"""Star Pattern.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qHkGEIIEOPUvK1g6TAA5oKGucz2oxp5U
"""

n = int(input("Enter any Value :"))
for i in range(1,n+1):
  for j in range(1,n +1):
    print(" * ", end = ' ')
  print(" ")

n = int(input("Enter any number:"))
for i in range (1, n+1):
    print(" *" * i)

n = int(input("Enter any number:"))
for i in range (1, n-1):
    print(" *" * n)

n = int(input("Enter any number:"))
for i in range (n, 0, -1):
    print(" *" * i)

n = int(input("Enter any number:"))
for i in range (n):
    print(" *" *(n-i))

n = int(input("Enter any number:"))
for i in range (n):
    print(" *" *(n-1))

rows = 5
for i in range(1, rows+1):
    for j in range(1 , i+1):
       print(j, end=" ")
    print()

n = int(input("Enter any number:"))
for i in range (1, n+1):
    print(i, end =' ')

ID = 23011011
p = "Abc"

n = int(input("Enter your ID: "))
m = str(input("Enter your Pass :"))
if (ID == n and p == m):
  print("Login Successful")
else:
  print("Login Failed")

n = int(input("Enter any Value :"))
for i in range(1,n):
  for j in range(1,n +1):
    print(i, end = ' ')
  print(" ")

n = int(input("Enter any Value :"))
for i in range(1,n):
  for j in range(1,n +1):
    print(j, end = ' ')
  print(" ")

n = int(input("Enter any Value :"))
for i in range(1,n):
  for j in range(i,n +i):
    print(j, end = ' ')
  print(" ")

n = int(input("Enter any Value :"))
for i in range(n, 0 ,-1):
  for j in range(i):
    print(chr(65), end = ' ')
  print(" ")

n = int(input("Enter any Value : "))

for i in range(n):
    for s in range(i):
        print("  ", end="")
    for j in range(n - i):
        print(chr(65 + j), end=" ")

    print()

for i in range(5, 0, -1):
    for s in range(5 - i):
        print("  ", end="")
    for j in range(0,i):
        print(chr(65 + j), end=" ")
    print()

